package encryption

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/hex"
	"fmt"
)

func DecryptContent(fileContent []byte) ([]byte, error) {
	// key should be 32 byte AES key - for demo purposes use example key
	// key will be generated by Diffie-Hellman key exchange later on and be passed
	// to this function as a parameter
	key, _ := hex.DecodeString("6368616e676520746869732070617373776f726420746f206120736563726574")
	if len(key) != 32 {
		return nil, fmt.Errorf("invalid key length: must be 32 bytes")
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err.Error())
	}

	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		panic(err.Error())
	}

	nonceSize := aesgcm.NonceSize()
	if len(fileContent) < nonceSize {
		return nil, fmt.Errorf("error: Encrypted data is too short (missing nonce)")
	}
	nonce := fileContent[:nonceSize]
	ciphertext := fileContent[nonceSize:]

	plaintext, err := aesgcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("error: Failed to encrypt data: %w", err)
	}

	return plaintext, nil
}
