package encryption

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
)

func EncryptContent(fileContent []byte) ([]byte, error) {
	// key should be 32 byte AES key - for demo purposes use example key
	// key will be generated by Diffie-Hellman key exchange later on and be passed
	// to this function as a parameter
	key, _ := hex.DecodeString("6368616e676520746869732070617373776f726420746f206120736563726574")
	if len(key) != 32 {
		return nil, fmt.Errorf("invalid key length: must be 32 bytes")
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("failed to create cipher: %w", err)
	}

	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("failed to create GCM: %w", err)
	}

	// Never use more than 2^32 random nonces with a given key because of the risk of a repeat
	nonce := make([]byte, aesgcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("failed to generate nonce: %w", err)
	}

	ciphertext := aesgcm.Seal(nonce, nonce, fileContent, nil)

	fmt.Println("Done! Ciphertext generated. Please wait while the encrypted file is being created.")

	return ciphertext, nil
}
